#!/usr/bin/perl
open PKG,$ARGV[0];
$prefix=$ARGV[1];
$prefix='' if($prefix eq '-');
$name='';
while(<PKG>){
	if(/pkgname=\(?(?<name>(\'?[\w\-]+\'?\s*)*)/){
		#chomp $+{name};
		$tmp=$+{name};
		chomp $tmp;
		$tmp=~s/\'?([^\'\s]+)\'?/$prefix\1-\*.pkg.tar.xz /g;
		$name.=$tmp;
		last;
	}
}
#while(<PKG>){
#	if(/pkgver=(?<ver>.+$)/){
#		chomp $+{ver};
#		$name.="-".$+{ver};
#		last;
#	}
#}
#while(<PKG>){
#	if(/pkgrel=(?<rel>.+$)/){
#		chomp $+{rel};
#		$name.="-".$+{rel};
#		last;
#	}
#}
print "$name\n";
