#!/bin/dash -f
MODKEY=Mod4
#WMII_FONT="xft:WenQuanYi Micro Hei Light Mono-9"
WMII_FONT="xft:sans-9"
WMII_TERM="urxvtc"
#WMII_NORMCOLORS='#000000 #333333 #000000'
#WMII_FOCUSCOLORS='#000000 #ffffff #000000'
status() {
	echo -n  label $(acpi -b | sed 's/Battery\s*[0-9]:\s*//g;s/\([0-9]\)[^0-9]*$/\1/g') '|' \
	$(sensors | grep --color=never 'Core' | sed 's/.*Core */CPU/g' | sed 's/(.*)//g') '|' \
	$(mpc | sed -r 'N;s/\n/ /g;N;s/\n/ /g;s/\[(playing|(p)aused)\]/\u\2/g;s/#//g;s/volume: */Vo:/g;s/\S*: *off//g;s/(\S\S)\S*: *on/\u\1 /g;s/\s+/ /g;s/\s+$//g;s|[0-9]+/[0-9]+||g;s/\s+[0-9]+:+[0-9]+//g;s/\([0-9]*%\)\s//g') '|' \
	$(date +"%Y/%m/%d,%a,%H:%M:%S")
}
startup() {
	urxvtd -q -o -f &
	xset m 8/5 3/2 
	witray -s 16 &
	wmiir write /rules <<!
	/MPlayer|VLC/ floating=on 
	/^ROX-Filer:/ group=0
	/wesnoth.*/ floating=on
	/Gimp/ floating=on
	/ncmpc_to_music_tag/ tags=music
	/Are you sure/ floating=on
	/^skype.*Options$/ floating=on
	/fetion/ floating=on
!
	/home/shui/cpuu.sh &
}
local_events(){
wi_events <<'!'
Event Unresponsive
	wmiir xwrite /client/$1/tags "UNRES"
Menu Client-3-Kill
	wmiir xwrite /client/$1/ctl slay &
Menu Client-3-Delete
	wmiir xwrite /client/$1/ctl kill &
#Event RightBarMouseDown
#	if [ "$2" = "weather" ]; then
#		if [ $1 = 1 ]; then
			#wmii9menu $(/home/shui/getweather)
#			wmii9menu showeather
#		fi
#	fi
Event ClientMouseDown
	if [ $2 = 3 ]; then
		wi_fnmenu Client $2 $1 &
	fi
	if [ $2 = 4 ]; then
		wmiir xwrite /tag/sel/ctl select up
	fi
	if [ $2 = 5 ]; then
		wmiir xwrite /tag/sel/ctl select down
	fi
	if [ $2 = 6 ]; then
		wmiir xwrite /tag/sel/ctl send sel left
	fi
	if [ $2 = 7 ]; then
		wmiir xwrite /tag/sel/ctl send sel right
	fi
KeyGroup Custom
Key $MODKEY-z
	mpc toggle 
Key $MODKEY-v
	mpc next
Key $MODKEY-c
	mpc prev
Key $MODKEY-x
	mpc shuffle
Key $MODKEY-Shift-r
	mpc repeat
Key $MODKEY-Shift-s
	mpc single
Key $MODKEY-w
	mpc volume +3
Key $MODKEY-q
	mpc volume -3
Key $MODKEY-r
	mpc seek +3%
Key $MODKEY-e
	mpc seek -3%
Key $MODKEY-Shift-z
	isplaying=$(mpc | grep -c '\[play')
	mpc update
	mpc clear
	mpc ls | mpc add
	[ $isplaying = 0 ] || mpc toggle
Key $MODKEY-Control-z
	isplaying=$(mpc | grep -c '\[play')
	mpc update 
	export tmpname="$(mpc listall | /home/shui/dlist.pl  | sort -u | wimenu)"
	echo "$tmpname" >> /home/shui/tmptmptmp
	if [ "x$tmpname" != "x" ]; then
		mpc clear
		echo $tmpname | mpc add
	fi
	[ $isplaying = 0 ] || mpc toggle
Key $MODKEY-Shift-b
	/home/shui/mysync.sh &
Key $MODKEY-Control-l
	xlock &
Key $MODKEY-Control-s
	ibus-daemon -r -d --xim
	feh --bg-scale ~/miku.jpg
	urxvtc -title ncmpc_to_music_tag -e ncmpc -m
	wicd-client &
	urxvtc
Key $MODKEY-Shift-x
	mpc playlist > ~/.mympcplaylist
	sed -r -i 's/(.*)/\L\1/' ~/.mympcplaylist
	export tmpname="$(cat ~/.mympcplaylist | wimenu)"
	if [ "x$tmpname" != "x" ]; then
		mpc play $(cat ~/.mympcplaylist | grep -F --color=never -n "$tmpname" | sed 's/:.*$//')
	fi
Key $MODKEY-mod1-space
	isplaying=$(mpc | grep -c '\[play')
	a=`echo 'Artist\nAlbum\nAlbumArtist\nTitle\nTrack\nName\nGenre\nDate\nComposer\nPerformer\nComment\nDisc' | wimenu`
	if [ "$?" = "0" ]; then
		b=`mpc list $a | wimenu`
	fi
	if [ "$?" = "0" ]; then
		mpc clear
		mpc search $a "$b" | mpc add
		[ $isplaying = 0 ] || mpc toggle
	fi
Key XF86AudioRaiseVolume
	amixer sset 'Master' 6%+
	echo -n label $(amixer sget 'Master' | grep --color=never 'Mono[^\[]*\[[0-9]*%\]' | sed -r 's/^.*\[([0-9]*%)\].*$/\1/') | wmiir write /rbar/status
Key XF86AudioLowerVolume
	amixer sset 'Master' 6%-
	echo -n label $(amixer sget 'Master' | grep --color=never 'Mono[^\[]*\[[0-9]*%\]' | sed -r 's/^.*\[([0-9]*%)\].*$/\1/') | wmiir write /rbar/status


!
true;
}
